spring:
  profiles:
    include:
      - jpa
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.SQL: debug
