spring:
  profiles: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cleanblogapp
    username: cleanblogapp
    password: cleanblogapp
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
---

spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  profiles: prod
  datasource:
    driver-class-name: ${spring.prod.datasource.driver-class-name}
    url: ${spring.prod.datasource.url}
    username: ${spring.prod.datasource.username}
    password: ${spring.prod.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
